options {
    directory "/var/bind";
    pid-file "/run/named/named.pid";
    version "get lost";
    allow-transfer {"none";};
    recursion no;
    listen-on { any; };
};

logging {
    channel named_log {
        file "/var/log/named/named.log" versions 3 size 5m;
        severity info;
        print-time yes;
    };
    category default { named_log; };
};
