#!/bin/sh

set -e

if [ "$1" != "configure" ]; then
    exit 0
fi

# Touch and set permisions on default log files on installation
update-rc.d vesta defaults >/dev/null
invoke-rc.d vesta start || true

echo "=== Restarting vesta ==="
service vesta stop
service vesta start
