LogFile /var/log/clamav/clamd.log
LogTime yes
LogFileMaxSize 10M
PidFile /run/clamav/clamd.pid
LocalSocket /run/clamav/clamd.sock
LocalSocketGroup clamav
LocalSocketMode 666
FixStaleSocket true
User clamav
ScanMail true
ScanArchive true
MaxDirectoryRecursion 15
MaxThreads 12
MaxConnectionQueueLength 15
DatabaseDirectory /var/lib/clamav
SelfCheck 3600
Foreground false
ScanPE true
ScanOLE2 true
ScanHTML true
ScanELF true
DetectPUA false
PhishingSignatures true
PhishingScanURLs true
StreamMaxLength 25M
