# Roundcube webmail Apache configuration for Vesta Control Panel

Alias /webmail /var/lib/roundcube/public_html
Alias /roundcube /var/lib/roundcube/public_html

<Directory /var/lib/roundcube/public_html/>
    Options +FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>

<Directory /var/lib/roundcube/config>
    Options -FollowSymLinks
    AllowOverride None
</Directory>

<Directory /var/lib/roundcube/temp>
    Options -FollowSymLinks
    AllowOverride None
    Require all denied
</Directory>

<Directory /var/lib/roundcube/logs>
    Options -FollowSymLinks
    AllowOverride None
    Require all denied
</Directory>
