#!/bin/sh
#
#   nginx
#   php-fpm
#
# chkconfig:   - 85 15
# description:  Run devit web server
# processname: devit
. /etc/rc.d/init.d/functions

# devit PATH
. /etc/profile.d/devit.sh

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ "$NETWORKING" = "no" ] && exit 0

nginx="/usr/local/devit/nginx/sbin/devit-nginx"
nignx_conf="/usr/local/devit/nginx/conf/nginx.conf"
php="/usr/local/devit/php/sbin/devit-php"
php_conf="/usr/local/devit/php/etc/php-fpm.conf"

devit_user=admin
devit_group=admin

start() {
    [ -x $nginx ] || exit 5
    [ -f $nignx_conf ] || exit 6
    [ -x $php ] || exit 1
    [ -f $php_conf ] || exit 2

    echo -n $"Starting devit-nginx: "
    daemon $nginx
    retval=$?
    echo
    [[ $retval -ne 0 ]] && exit $retval

    echo -n $"Starting devit-php: "
    daemon $php
    echo
    return $retval
}

stop() {
    echo -n $"Stopping devit-nginx: "
    killproc -p /var/run/devit-nginx.pid devit-nginx -QUIT
    retval=$?
    echo
    [ -f ${pidfile} ] && /bin/rm -f ${pidfile}
    [[ $retval -ne 0 ]] && exit $retval

    echo -n $"Stopping devit-php: "
    killproc -p /var/run/devit-php.pid devit-php -QUIT
    retval=$?
    echo
    [ -f /var/run/devit-php.pid ] && /bin/rm -f /var/run/devit-php.pid
    [ -f /var/run/devit-php.sock ] && /bin/rm -f /var/run/devit-php.sock
    return $retval
}

restart(){
    stop
    start
}

reload() {
    echo -n $"Reloading devit-nginx: "
    killproc -p /var/run/devit-nginx.pid devit-nginx -USR2
    retval=$?
    echo
    [[ $retval -ne 0 ]] && exit $retval

    echo -n $"Reloading devit-php: "
    killproc -p /var/run/devit-php.pid devit-php -USR2
    retval=$?
    echo
    return $retval
}

rh_status(){
    status -p /var/run/devit-nginx.pid devit-nginx
    status -p /var/run/devit-php.pid devit-php
}

case "$1" in
    start)
        start;;
    stop)
        stop;;
    restart)
        restart;;
    reload)
        reload;;
    status)
        rh_status;;
    *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 3
esac
