mail_privileged_group = mail
mail_access_groups = mail
mail_driver = maildir
mail_path = %{home}/mail/%{user | domain}/%{user | username}
pop3_uidl_format = %{uid | substr(0, 8)}%{uidvalidity | substr(0, 8)}
namespace inbox {
  inbox = yes
}
first_valid_uid = 1000
mbox_write_locks = fcntl
