#!/bin/bash

# Run triggers only on updates
if [ ! -e "/usr/local/vesta/data/users/admin" ]; then
    exit
fi

# Run triggers
if [ -x "/root/vesta-patch.sh" ]; then
    /root/vesta-patch.sh
fi

check_apt=$(grep -c 'vesta.hostingpanel.dev' /etc/apt/sources.list.d/vesta.list)
if [ "$check_apt" -eq 1 ]; then
    wget -O - http://apt.myvestacp.com/deb_signing.key | sudo apt-key add -
    codename="$(cat /etc/os-release |grep VERSION= |cut -f 2 -d \(|cut -f 1 -d \))"
    echo "deb http://apt.myvestacp.com/$codename/ $codename vesta" > /etc/apt/sources.list.d/vesta.list
fi

crontab -l | { cat; echo "10 2 * * 6 sudo find /home/*/tmp/ -type f -mtime +5 -exec rm {} \;"; } | crontab -

touch /var/lib/clamav/clamd.sock
chown clamav:clamav /var/lib/clamav/clamd.sock
sed -i "s#/var/run/clamav/clamd.ctl#/var/lib/clamav/clamd.sock#g" /etc/clamav/clamd.conf
systemctl restart clamav-daemon
systemctl restart clamav-freshclam

exit 0
